config/routes.rb
Hanjay::Application.routes.draw do

  

  
  resources :news, :only => [:index, :show]
 
  match "/admin/createAdmin" => "admin#createAdmin", :via => :post
  match '/admin/showAdmins' => 'admin#showAdmins' 
  match '/admin/deleteAdmin/:id' => 'admin#deleteAdmin' , :via => :delete
  
  match "/admin/loginCheck" => "admin#loginCheck", :via => :post
  match "/admin/update" => "admin#update", :via => :put
  match '/admin' => 'admin/news#index'    
  
  namespace :admin do
    get "sign_up", "log_in", "log_out", "edit"
    

    resources :events
    resources :flaws

    resources :news, :except => :new do
      match 'uploadPhoto' => 'news#createPhoto', :via => [:post]
      match 'deletePhoto/:id' => 'news#destroyPhoto', :via => [:delete]
    end
    
  end

  resources :flaws
  resources :events
  
  match "pages/:id"		=> "static_page#show"
  resources :pages, :only => :show
  
  resources :news, :only => [:index, :show]
  
  root :to => "static_page#index"
  
  
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  layout false, :only => [:index]
  def index
  	@news = News.where( "status = 'enable'" ).order('date DESC').page(params[:page]).limit(5)
  	
  	@flaws = Flaw.where("status = 'enable'").order('date DESC').limit(5)
  	
  	@event = Event.where( "status = ? AND date > ?  ","enable", Time.now.tomorrow ).order( "date ASC" ).first
  	
  end
  
  def show
  
  	respond_to do | format |
  		format.html { render :template => "static_page/#{params[ :id ]}" }
  	end
  
  end
  
  def intro 	
  end
end

app/views/static_page/_meta.html.erb
<%= ( render :partial => "static_page/meta/" + params[ :id ] ) if !params[ :id ].nil? %>

app/views/static_page/about.erb
<section> 
  <hgroup>
  <h2>支援與服務</h2>
  <p>若想瞭解更多關於漢杰的服務或有任何疑問</p>
  </hgroup>
  <div id="content">
  <div class="left">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="20%"><imgsrc="<%= image_path("sup-02.jpg") %>" width="68" height="68"></td>
    <td width="80%">歡迎您來電洽詢<br>
      <strong style="font-size:35px">02-7737-7001</strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-03.jpg") %>" width="71" height="72"></td>
    <td>寫封Email給我們<br>
      <strong><a href="mailto:sales@hanjay.com">sales@hanjay.com</a></strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-04.jpg") %>" width="68" height="68"></td>
    <td>也可利用傳真<br>
      <strong>02-2799-2677 </strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-05.jpg") %>" width="68" height="68"></td>
    <td>或親自來訪<br>
      <strong style="font-size:18px">台北市內湖區瑞光路 607 號 4 樓</strong></td>
  </tr>
</table>

  </div><!--left-->
  <div class="right">
  </div><!--right-->
  </div> <!--content-->
  </section>

app/views/static_page/index.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<![endif]-->
<meta charset="utf-8">
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />
<meta name="keywords" content="資訊安全, 網路安全, 個資, 個人資料, 雲端 "/>
<meta name="description" content="雲端時代來臨，個資法頒布，企業的資訊安全計劃準備好了嗎？機密文件傳輸，珍貴的客戶個人資料，都可能是有心人士的主要目標，漢杰科技提供資訊安全顧問四大服務，與強力的資訊安全夥伴，一起為企業打造最放心的網路安全方案。"/>
<link rel="SHORTCUT ICON" href="/images/favicon.ico"/>
<link rel="image_src" href="/images/thumb.jpg"/>
<meta property="og:title" content="漢杰科技-網路安全風險診斷專家"/>
<meta property="og:description" content="雲端時代來臨，個資法頒布，企業的資訊安全計劃準備好了嗎？機密文件傳輸，珍貴的客戶個人資料，都可能是有心人士的主要目標，漢杰科技提供資訊安全顧問四大服務，與強力的資訊安全夥伴，一起為企業打造最安心的網路安全方案。"/>
<meta property="og:site_name" content="漢杰科技-網路安全風險診斷專家"/>
<meta property="og:image" content="www.hanjay.com/images/thumb.jpg"/>
<meta property="og:type" content="company"/>
<meta name="google-site-verification" content="QvFuzKbLBaXARSFAOzJm56CdUEoR5QAoI3fyudVb90w" />
<title>漢杰科技-網路安全風險診斷專家</title>
<%= stylesheet_link_tag "reset", :media => :all %>
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "index", :media => :all %>

<%= javascript_include_tag "application" %>
<!--script>
$(document).ready(function(){
	$(".iframe").colorbox({iframe:true, width:"80%", height:"80%"});
});
</script-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40239827-1', 'hanjay.com');
  ga('send', 'pageview');

</script>
</head>

<body>

<header _height="none">
  <section>
    <h1><a href="<%= root_url %>">HANJAY</a></h1>
    <nav> <a href="<%= root_url + "#about-link" %>">關於漢杰</a> <a href="<%= root_url + "#update-link" %>">最新消息</a> <a href="<%= page_path( :id => "support" ) %>">支援與服務</a> <a href="<%= root_url + "#partner-link" %>">夥伴與方案</a> <a href="<%= root_url + "#service-link" %>">漢杰服務</a></nav>
  </section>
</header>

<article id="intro">
  <section>
    <h3>網路安全風險診斷專家</h3>
    <p>透過量化、視覺化的資安風險評量報告，迅速明瞭目前的網路環境狀況<br>
      漢杰科技團隊擁有跨國資訊安全服務經驗與獨立安全軟體開發鑑識能力<br>
      提供內網《資料外洩、殭屍電腦、間諜程式、APT 攻擊》查核與電腦鑑<br>
      識服務</p>
    <div id="btn"><a href="<%= page_path( :id => "support" ) %>"></a> </div>
    <div id="actlink"><%= link_to "近期活動：#{@event.title}⋯more", @event.link if !@event.nil? %></div>
  </section>
</article>
<h2 id="service-1-h2">
<a id="service-link" style="position:absolute;top:-85px"></a>
  <section> </section>
</h2>
<article id="service-1-1">
  <section>
    <h3>資料外洩查核服務</h3>
    <p>漢杰科技提供機敏資料外洩查核與防護方案，透過資料庫安全存取稽核、Web 應用層穿透威脅分析，安全弱點控制，可積極協助與管制各樣潛藏的資料外洩風險。 <!--a href="#">... more</a--></p>
    <ul>
      <li><a class="iframe">資料庫安全稽核</a></li>
      <li><a class="iframe">Web 應用層穿透威脅分析</a></li>
      <li><a class="iframe">資料庫高風險弱點查核控制</a></li>
      <li><a class="iframe">機敏(個)資料盤點、風險評鑑與加密防護</a></li>
      <li><a class="iframe">機敏資料使用、管理、銷毀驗證分析</a></li>
    </ul>
  </section>
</article>
<article id="service-1-2">
  <section>
    <h3>內網惡意流量分析服務</h3>
    <p>漢杰科技協助客戶進行網路應用層惡意流量鑑識分析，此分析可清楚診斷內網不當流量來源與活動分佈，掃除殭屍電腦植入與 APT 攻擊威脅，並積極提供內網 QoS 管理，可滿足網路營運不中斷，不延遲的目標。 <!--a href="#">... more</a--></p>
    <ul>
      <li><a class="iframe">分析目標網路，高風險惡意流量來源與影響分佈</a></li>
      <li><a class="iframe">警示網路中存在的殭屍電腦 (Botnet) 與不明 Tunnel 活動</a></li>
      <li><a class="iframe">分析目標網路 Top 10 的各項高流量應用行為</a></li>
      <li><a class="iframe">提出目標網路可修正之風險控管措施</a></li>
    </ul>
  </section>
</article>
<h2 id="service-2-h2">
  <section> </section>
</h2>
<article id="service-2-1">
  <section>
    <h3>安全弱點掃描服務</h3>
    <p>漢杰科技提供安全弱點掃描服務，可自雲端與近端2種方式進行，並特別針對高風險弱點做覆查與修補建議，風險差異性分析報告亦可滿足客戶 ISO27001 / 20000 之驗證要求。 <!--a href="#">... more</a--></p>
    <ul>
      <li><a class="iframe">提供 IPv4/IPv6 雙協定弱點分析報告</a></li>
      <li><a class="iframe">雲端掃描或隔離環境之近端掃描</a></li>
      <li><a class="iframe">差異性弱點報表與修補追蹤</a></li>
      <li><a class="iframe">高風險弱點複驗</a></li>
    </ul>
  </section>
</article>
<article id="service-2-2">
  <section>
    <h3>電腦鑑識與數位證據服務</h3>
    <p>提供資訊資產管理與電腦鑑識服務，針對機密敏感性資料的不當使用提供預防、偵測、回應3項策略性建議與實務稽查分析，可滿足客戶數位證據的法院舉證效力。 <!--a href="#">... more</a--></p>
    <ul>
      <li><a class="iframe">數位資料封存、刪除重建與無汙染證據保全</a></li>
      <li><a class="iframe">特徵資料存取軌跡與鑑識</a></li>
      <li><a class="iframe">系統拋轉比對分析(供應商與客戶)</a></li>
      <li><a class="iframe">高風險目標鑑識預防、合理性偵測與防護線建立</a></li>
    </ul>
  </section>
</article>
<article id="partner">
<a id="partner-link" style="position:absolute;top:-85px"></a>
  <section>
    <h3>夥伴與方案</h3>
    <p>漢杰科技與多家業界知名技術公司合作，提供最適宜的工具與產品解決方案</p>
    <ul>
           <li><a href="http://www.bluecoat.com/" target="_blank">BlueCoat</a></li>
	       <li><a href="http://www.nii.org.tw/" target="_blank">NII</a></li>
	       <li><a href="http://www.citrix.com.tw/" target="_blank">Citrix</a></li>
	       <li><a href="http://www.armorize.com/" target="_blank">Proofpoint/ Armorize</a></li>
	       <li><a href="http://www.cobrasonic.com/tw/" target="_blank">Cobrasoinc</a></li>
	       <li><a href="http://www.sinpao.com.tw/index.html" target="_blank">Sinpao</a></li>
	       <li><a href="http://www.emc.com/domains/rsa/index.htm" target="_blank">EMC/RSA</a></li>
	       <li><a href="http://www.trustview.com.tw/" target="_blank">TrustView</a></li>
	       <li><a href="http://www.guidancesoftware.com/" target="_blank">Encase</a></li>
	       <li><a href="http://www.broadweb.com/" target="_blank">Trendmicro/BWEX</a></li>
	       <li><a href="http://www.fireeye.com/" target="_blank">FireEye</a></li>
	       <li><a href="http://www.warevalley.com/" target="_blank">WareValley/Chakra</a></li>
	       <li><a href="http://formosaauditor.com/index-tw.php" target="_blank">FormosaAuditor</a></li>
	       <li><a href="http://tw.websense.com/content/home.aspx" target="_blank">Websense</a></li>
	       <li><a href="http://www8.hp.com/tw/zh/business-solutions/solution.html?compURI=1079733#tab=TAB1" target="_blank">HP</a></li>
	       <li><a href="http://www.xecure-lab.com/zhTW/index.html" target="_blank">Xecure Lab</a></li>
	       <li><a href="http://www.kpmg.com/tw/zh/Pages/default.aspx" target="_blank">KPMG</a></li>
	       <li><a href="http://www.xceedium.com/" target="_blank">Xceedium</a></li>
    </ul>
  </section>
</article>
<article id="update">
<a id="update-link" style="position:absolute;top:-85px"></a>
  <section>
    <div id="bulletin">
      <h4>安全弱點通報</h4>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <% @flaws.each do | flaw | %>
        <tr>
          <td width="22%">+   <%= flaw.date.to_s(:date_slashed) %></td>
          <td width="78%"><%= link_to flaw.issue, flaws_path %></td>
        </tr>      
      <% end %>
      </table>
    </div>
    <div id="news">
      <h4>最新消息</h4>
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <% @news.each do | news | %>
        <tr>
          <td width="22%">+   <%= news.date.to_s(:date_slashed) %></td>
          <td width="78%"><%= link_to news.name, news_path(news.id.to_s) %></td>
        </tr>      
      <% end %>          
      </table>
    </div>
  </section>
</article>
<article id="about">
<a id="about-link" style="position:absolute;top:-85px"></a>
  <section>
    <div id="found">
      <h4>關於漢杰科技</h4>
      <p>漢杰科技成立於2012年，主要營業核心在於提供企業與政府單位人性化的資訊安全解決方案。<br>
        漢杰科技的成員皆是資訊安全市場早期的拓荒者，成員普遍擁有十年以上資訊安全的資歷，服務客<br>
        群遍及亞洲地區，是台灣少數擁用跨國資訊安全專案與獨立安全軟體開發經驗的技術服務團隊。</p>
    </div>
    <!--found-->
    <div id="idea">
      <h4>經營理念</h4>
      <div id="idea-box">
        <div class="box">
          <h5>誠信</h5>
          <p>最基本也最重要的理念。我們說真話；我們不誇張，同時我們絕不容許貪污，<strong>一旦做出承諾必定全力以赴</strong>，我們用人的首要條件是品格與才能，絕不是「關係」。</p>
        </div>
        <div class="box" style="margin:0 5%">
          <h5>承諾</h5>
          <p>漢杰科技堅持信守對客戶、供應商、員工、股東及社會的承諾。漢杰科技相信成功來自於付出與回饋，<strong>信守與權益關係人的承諾是漢杰科技的清楚信念</strong>，漢杰科技會盡力照顧所有權益關係人的權益。</p>
        </div>
        <div class="box">
          <h5>客戶信任</h5>
          <p>客戶是我們的夥伴，因此我們<strong>優先考慮客戶的需求</strong>。我們努力與客戶建立深遠的夥伴關係，深耕與服務並且成為客戶信賴的長期夥伴。</p>
        </div>
      </div>
      <!--idea-box--> 
    </div>
    <!--idea--> 
  </section>
</article>

<%= render :partial => "layouts/footer" %>
</body>
</html>

app/views/static_page/partner-link.erb
<section> 
  <hgroup>
  <h2>支援與服務</h2>
  <p>若想瞭解更多關於漢杰的服務或有任何疑問</p>
  </hgroup>
  <div id="content">
  <div class="left">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="20%"><imgsrc="<%= image_path("sup-02.jpg") %>" width="68" height="68"></td>
    <td width="80%">歡迎您來電洽詢<br>
      <strong style="font-size:35px">02-7737-7001</strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-03.jpg") %>" width="71" height="72"></td>
    <td>寫封Email給我們<br>
      <strong><a href="mailto:sales@hanjay.com">sales@hanjay.com</a></strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-04.jpg") %>" width="68" height="68"></td>
    <td>也可利用傳真<br>
      <strong>02-2799-2677 </strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-05.jpg") %>" width="68" height="68"></td>
    <td>或親自來訪<br>
      <strong style="font-size:18px">台北市內湖區瑞光路 607 號 4 樓</strong></td>
  </tr>
</table>

  </div><!--left-->
  <div class="right">
  </div><!--right-->
  </div> <!--content-->
  </section>

app/views/static_page/service-link.erb
<section> 
  <hgroup>
  <h2>支援與服務</h2>
  <p>若想瞭解更多關於漢杰的服務或有任何疑問</p>
  </hgroup>
  <div id="content">
  <div class="left">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="20%"><imgsrc="<%= image_path("sup-02.jpg") %>" width="68" height="68"></td>
    <td width="80%">歡迎您來電洽詢<br>
      <strong style="font-size:35px">02-7737-7001</strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-03.jpg") %>" width="71" height="72"></td>
    <td>寫封Email給我們<br>
      <strong><a href="mailto:sales@hanjay.com">sales@hanjay.com</a></strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-04.jpg") %>" width="68" height="68"></td>
    <td>也可利用傳真<br>
      <strong>02-2799-2677 </strong></td>
  </tr>
  <tr>
    <td><imgsrc="<%= image_path("sup-05.jpg") %>" width="68" height="68"></td>
    <td>或親自來訪<br>
      <strong style="font-size:18px">台北市內湖區瑞光路 607 號 4 樓</strong></td>
  </tr>
</table>

  </div><!--left-->
  <div class="right">
  </div><!--right-->
  </div> <!--content-->
  </section>

app/views/static_page/support.html.erb
<%= stylesheet_link_tag "support", :media => :all %>

<section> 
  <hgroup>
  <h2>支援與服務</h2>
  <p>若想瞭解更多關於漢杰的服務或有任何疑問</p>
  </hgroup>
  <div id="content">
  <div class="left">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="20%"><img src="<%= image_path("sup-02.jpg") %>" width="68" height="68"></td>
    <td width="80%">歡迎您來電洽詢<br>
      <strong style="font-size:35px">02-2910-1125</strong></td>
  </tr>
  <tr>
    <td><a href="mailto:sales@hanjay.com" target="_blank"><img src="<%= image_path("sup-03.jpg") %>" width="71" height="72"></a></td>
    <td>寫封Email給我們<br>
      <strong><a href="mailto:sales@hanjay.com" target="_blank">sales@hanjay.com</a></strong></td>
  </tr>
  <tr>
    <td><img src="<%= image_path("sup-05.jpg") %>" width="68" height="68"></td>
    <td>或親自來訪<br>
      <strong style="font-size:18px">11052 台北市信義區基隆路二段 22 號 6 樓之 6</strong></td>
  </tr>
</table>

  </div><!--left-->
  <div class="right">
  
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3615.0583798055627!2d121.55657971500621!3d25.03209278397326!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442abca13fc15cf%3A0xe0f2dafc6976dc84!2zMTEw5Y-w5YyX5biC5L-h576p5Y2A5Z-66ZqG6Lev5LqM5q61MjLomZ8!5e0!3m2!1szh-TW!2stw!4v1459934609858" width="500" height="340" frameborder="0" style="border:0"></iframe>
  
  </div><!--right-->
  </div> <!--content-->
  </section>
  
  <script>
  	$(document).ready(function() {
	  $('nav a[href*=support]').addClass('active');
	  	
  	});
  </script>