config/routes.rb
Hanjay::Application.routes.draw do

  

  
  resources :news, :only => [:index, :show]
 
  match "/admin/createAdmin" => "admin#createAdmin", :via => :post
  match '/admin/showAdmins' => 'admin#showAdmins' 
  match '/admin/deleteAdmin/:id' => 'admin#deleteAdmin' , :via => :delete
  
  match "/admin/loginCheck" => "admin#loginCheck", :via => :post
  match "/admin/update" => "admin#update", :via => :put
  match '/admin' => 'admin/news#index'    
  
  namespace :admin do
    get "sign_up", "log_in", "log_out", "edit"
    

    resources :events
    resources :flaws

    resources :news, :except => :new do
      match 'uploadPhoto' => 'news#createPhoto', :via => [:post]
      match 'deletePhoto/:id' => 'news#destroyPhoto', :via => [:delete]
    end
    
  end

  resources :flaws
  resources :events
  
  match "pages/:id"		=> "static_page#show"
  resources :pages, :only => :show
  
  resources :news, :only => [:index, :show]
  
  root :to => "static_page#index"
  
  
end

app/models/event.rb
#encoding: utf-8
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :link, :location, :period, :status, :title
  
  validates :title, :presence => { :message => "活動標題不得為空"}
  
  validates :link, :format => { :with => /^http(s)?:\/\/[\w\.\-\_\/:\?\%\=\;\&\_\-\+]+$/, :message => "請輸入正確網址格式" }
    
  after_initialize :fill_defaults
  before_create :fill_defaults
   
  def fill_defaults
  	if self.status.nil?
  		self.status = "disable"
  	end
  	
  	if self.date.nil?
  		self.date = Time.now
  	end
  end

  
end

app/controllers/admin/events_controller.rb
# encoding: utf-8
class Admin::EventsController < ApplicationController

	layout "admin"

	def index
		
		where_clause = ''
		
		case params[ :status ]
			when "disable"
				where_clause = "status <> 'enable'"
			when "expired"
				where_clause = "date < '#{Time.now.tomorrow.at_beginning_of_day.to_s}'"
			else
				where_clause = "status = 'enable' AND date >= '#{Time.now.tomorrow.at_beginning_of_day.to_s}'"
				
		end
		
		@events = Event.where(where_clause).order( "date DESC" ).page( params[:page] ).per(10)
	
	end
	
	def show
	
		@event = Event.find( params[ :id ] )
	
	end
	
	def edit
	
		@event = Event.find( params[ :id ] )
	
	end
	
	def new
		@event = Event.new
	
	end
	
	def create
		@event = Event.new( params[ :event ] )
		
		
		respond_to do | format |
			if @event.save
				flash[ :notice ] =  "課程已建立"
				format.html { redirect_to admin_events_path }
			else
				format.html { render :new }
			end 
		end
		
	
	end
	
	def update
	
		@event = Event.find( params[ :id ] )
		
		respond_to do | format |
			if @event.update_attributes( params[ :event ] )
				flash[ :notice ] =  "課程更新完成"
				format.html { render action: "show" }
			else
				format.html { render action: "new" }
			end
		end
	
	end
	
	def destroy
		@event = Event.find(params[:id])
		
		@event.destroy
		
		respond_to do | format |
			format.html { redirect_to admin_events_path }
		end
	
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :get_events

	def index
	
	
	end
	
	def show
	
		@event = Event.find( params[ :id ] )
		
		respond_to do | format |
			format.html { render :index, :anchor => "event_" + @event.id.to_s }
		end
	
	end
	
private
	def get_events		
		@events = Event.where( "status = ? AND date > ?  ","enable", Time.now.tomorrow.beginning_of_day ).order( "date DESC" )
	end	
	
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_form.html.erb
<% if @event.errors.any?  %>
<script>
	var message = "<%= @event.errors.count.to_s + "個問題必須修正：" %>" + " <br />";
	<% @event.errors.full_messages.each do | m | %>
	message += "<%= m %><br />";
	<% end %>

	Alertify.dialog.alert(message);	
</script>
<% end %>

<%= form_for([:admin, @event]) do |f| %>

    <section class="title">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th><%= f.label :title, "活動名稱" %></th>
          <td><%= f.text_field :title, :placeholder => "請輸入活動名稱" %></td>
        </tr>
      </table>
    </section>
    <!--title-->
    <section class="text text-edit">
      <div class="half">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>    
            <th valign="top"><%= f.label :date, "日期：" %></th>
            <td><%= f.text_field :date, :placeholder => "請選擇活動日期", :class => "datePicker", :value =>@event.date.to_s( :date )  %></td>
          </tr>
        </table>
      </div>
      <div class="half">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th valign="top"><%= f.label :period, "時間：" %></th>
            <td><%= f.text_field :period, :placeholder => "請手動輸入時間" %></td>
          </tr>
        </table>
      </div>
      <div class="one">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th valign="top"><%= f.label :location, "地點：" %></th>
            <td><%= f.text_field :location, :placeholder => "請輸入地點" %></td>
          </tr>
        </table>
      </div>
      <div class="one">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th valign="top"><%= f.label :description, "內容：" %></th>
            <td><%= f.text_area :description, :class => "autogrow" %></td>
          </tr>
        </table>
      </div>
      <div class="one">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th valign="top"><%= f.label :link, "URL：" %></th>
            <td><%= f.text_field :link, :placeholder => "http://www.example.com.tw" %></td>
          </tr>
        </table>
      </div>
      <div class="one">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th><%= f.label :status, "顯示？" %></th>
            <td>
            	<%= f.check_box :status, { :checked => ("checked" if @event.status == "enable"), :class => "checkbox" }, "enable" %>
              ( 若無勾選則不發佈 )</td>
          </tr>
        </table>
      </div>
    </section>
    <!--text-->
    <section class="button"><a href="javascript:$('#eventSubmit').click();"><%= image_submit_tag "save.png", :id => "eventSubmit" %> 儲存</a><a href="<%= admin_events_path %>"><img src="<%= image_path "cancel.png" %>">取消</a> </section>
    <!--button--> 
<% end %>

app/views/admin/events/edit.html.erb
<section class="hgroup">
  <h2>編輯頁面</h2>
  <p>-進行中</p>
</section>

<%= render 'form' %>

app/views/admin/events/index.html.erb
<section class="category">
  <ul>
    <li <%= ' class="active"'.html_safe if params[:status].nil? || params[:status] == "enable" %> ><a href="<%= admin_events_path( :status => "enable" ) %>">進行中</a></li>
    <li <%= ' class="active"'.html_safe if params[:status] == "disable" %> ><a href="<%= admin_events_path( :status => "disable" ) %>">未發佈</a></li>
    <li <%= ' class="active"'.html_safe if params[:status] == "expired" %> ><a href="<%= admin_events_path( :status => "expired" ) %>">已過期</a></li>
  </ul>
</section>
<!--category-->
<section class="button"> <a href="<%= new_admin_event_path %>"><img src="<%= image_path("add.png") %>">新增活動</a> </section>
<!--button-->
<section class="list">

  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <th align="left" class="x0 x2">日期</th>
      <th align="left">活動名稱</th>
      <th align="left" class="x0 x1">編輯</th>
      <th align="left" class="x1">刪除</th>
    </tr>
    
	<% @events.each do |event| %>
	  <tr>
	      <td class="x0"><%= event.date.to_s(:date) %></td>
	      <td><a href="#"><%= link_to event.title, admin_event_path(event) %></a></td>
	      <td class="x0"><%= link_to image_tag("edit.png"), edit_admin_event_path(event) %></td>
	      <td class="delete"><%= link_to image_tag("delete.png"), admin_event_path( event ), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
  </table>
</section>

  <%= paginate @events, :theme => 'admin' %>

app/views/admin/events/new.html.erb
<section class="hgroup">
  <h2>新增活動</h2>
</section>

<%= render 'form' %>

app/views/admin/events/show.html.erb
<section class="hgroup">
  <h2>預覽頁面</h2>
  <p>-進行中</p>
</section>
<!--hgroup-->
<section class="title">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <th><%= @event.date.to_s( :date ) %></th>
      <td><%= @event.title %>&nbsp;</td>
    </tr>
  </table>
</section>
<!--title-->
<section class="text text-show">
  <div class="one">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th valign="top">時間：</th>
        <td><%= @event.period %>&nbsp;</td>
      </tr>
    </table>
  </div>
  <div class="one">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th valign="top">地點：</th>
        <td><%= @event.location %>&nbsp;</td>
      </tr>
    </table>
  </div>
  <div class="one">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th valign="top">內容：</th>
        <td><%= @event.description %>&nbsp;</td>
      </tr>
    </table>
  </div>
  <div class="one">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th>顯示？</th>
        <td><%= @event.status == 'enable' ? '是' : '否' %></td>
      </tr>
    </table>
  </div>
</section>
<!--text-->
<section class="button"> <%= link_to image_tag("edit.png") + "編輯", edit_admin_event_path(@event) %><%= link_to image_tag("back.png") + "返回", admin_events_path %></section>
<!--button--> 
</article>