config/routes.rb
Hanjay::Application.routes.draw do

  

  
  resources :news, :only => [:index, :show]
 
  match "/admin/createAdmin" => "admin#createAdmin", :via => :post
  match '/admin/showAdmins' => 'admin#showAdmins' 
  match '/admin/deleteAdmin/:id' => 'admin#deleteAdmin' , :via => :delete
  
  match "/admin/loginCheck" => "admin#loginCheck", :via => :post
  match "/admin/update" => "admin#update", :via => :put
  match '/admin' => 'admin/news#index'    
  
  namespace :admin do
    get "sign_up", "log_in", "log_out", "edit"
    

    resources :events
    resources :flaws

    resources :news, :except => :new do
      match 'uploadPhoto' => 'news#createPhoto', :via => [:post]
      match 'deletePhoto/:id' => 'news#destroyPhoto', :via => [:delete]
    end
    
  end

  resources :flaws
  resources :events
  
  match "pages/:id"		=> "static_page#show"
  resources :pages, :only => :show
  
  resources :news, :only => [:index, :show]
  
  root :to => "static_page#index"
  
  
end

app/models/flaw.rb
# encoding: utf-8
class Flaw < ActiveRecord::Base
  attr_accessible :date, :issue, :status
  
  validates :issue, :presence => { :message => "議題不得為空白" }
  
  after_initialize :fill_defaults
  before_save :fill_defaults
  
  def fill_defaults
  
  	if self.status.nil?
  		self.status = "disable"
  	end
  	
  	if self.date.nil?
  		self.date = Time.now
  	end
  
  end
  
end

app/controllers/admin/flaws_controller.rb
# encoding: utf-8
class Admin::FlawsController < ApplicationController

  layout "admin"

  # GET /flaws
  # GET /flaws.json
  def index
    @flaws = Flaw.order("date DESC, created_at DESC").page( params[:page] ).per(10)
    
    @flaw = Flaw.new
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flaws }
    end
  end

  # GET /flaws/1
  # GET /flaws/1.json
  def show
    @flaw = Flaw.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flaw }
    end
  end

  # GET /flaws/new
  # GET /flaws/new.json
  def new
    @flaw = Flaw.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flaw }
    end
  end

  # GET /flaws/1/edit
  def edit
    @flaw = Flaw.find(params[:id])
  end

  # POST /flaws
  # POST /flaws.json
  def create
    @flaw = Flaw.new(params[:flaw])

    respond_to do |format|
      if @flaw.save
        format.html { redirect_to admin_flaws_path, notice: '新增完成' }
        format.json { render json: @flaw, status: :created, location: @flaw }
      else
      	@flaws = Flaw.order("date DESC, created_at DESC").all
        format.html { render :index }
        format.json { render json: @flaw.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flaws/1
  # PUT /flaws/1.json
  def update
    @flaw = Flaw.find(params[:id])

    respond_to do |format|
      if @flaw.update_attributes(params[:flaw])
        format.html { redirect_to admin_flaws_path, notice: '弱點通報更新完成' }
        format.js {}
      else
        format.html { render action: "edit" }
        format.json { render json: @flaw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flaws/1
  # DELETE /flaws/1.json
  def destroy
    @flaw = Flaw.find(params[:id])
    @flaw.destroy

    respond_to do |format|
      format.html { redirect_to admin_flaws_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/flaws_controller.rb
class FlawsController < ApplicationController

  # GET /flaws
  # GET /flaws.json
  def index
    @flaws = Flaw.where( :status => "enable" ).order("date DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flaws }
    end
  end
end

app/helpers/flaws_helper.rb
module FlawsHelper
end

app/views/admin/flaws/index.html.erb
<% if @flaw.errors.any?  %>
<script>
	var message = "";
	<% @flaw.errors.full_messages.each do | m | %>
	message += "<%= m %><br />";
	<% end %>

	Alertify.dialog.alert(message);	
</script>
<% end %>
<%= form_for([:admin, @flaw]) do | f | %>
<section class="text text-edit">
	
  <div class="quarter">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th valign="top"><%= f.label :date, "發佈日期：" %></th>
        <td><%= f.text_field :date, :placeholder => "請選擇活動日期", :class => "datePicker", :value => Time.now.to_s( :date )  %></td>
      </tr>
    </table>
  </div>
  <div class="remainder">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th valign="top"><%= f.label :issue, "文章標題：" %></th>
        <td><%= f.text_field :issue %><%= "<div style=\"color: red;\">#{@flaw.errors.messages[ :issue ][0]}</div>".html_safe if @flaw.errors.any? && !@flaw.errors.messages[ :issue ].nil? %></td>
      </tr>
    </table>
  </div>
  <div class="one">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th><%= f.label :status, "前台顯示？" %></th>
        <td><%= f.check_box :status, { :checked => ("checked" if @flaw.status == "enable"), :class => "checkbox" }, "enable" %>
          ( 若無勾選則不發佈 )</td>
      </tr>
    </table>
  </div>
</section>
<!--text-->
<section class="button"> <a href="javascript:$('form#new_flaw').submit();"><img src="<%= image_path("add.png") %>">新增</a> </section>
  <% end %>
<!--button-->
<section class="hgroup">
  <h2>弱點通報列表</h2>
  <p>( 可點擊圖示更換發佈狀態 )</p>
</section>
<!--hgroup-->
<section class="list">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <th align="left" class="x0 x1">發佈</th>
      <th align="left" class="x0 x2">日期</th>
      <th align="left">標題</th>
      <th align="left" class="x1">刪除</th>
    </tr>
    
<% @flaws.each do |flaw| %>
    <tr>
      <td class="x0"><%= link_to image_tag( (flaw.status == 'enable' ? "check.png" : "cancel.png"), { :id => "flaw_#{flaw.id}_status" } ), admin_flaw_path( flaw, "flaw[status]" => (flaw.status == 'enable' ? "disable" : "enable")  ), :method => :put , :remote => true %></td>
      <td class="x0"><%= flaw.date.to_s( :date ) %></td>
      <td><a href="#"><%= flaw.issue %></a></td>
      <td class="delete"><%= link_to image_tag("delete.png"), admin_flaw_path(flaw), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
  </table>
</section>
<!--list--> 

app/views/admin/flaws/update.js.erb
$("#flaw_<%= @flaw.id %>_status").attr('src', '<%= image_path( (@flaw.status == 'enable' ? "check.png" : "cancel.png") ) %>').parent().attr('href', '<%= admin_flaw_path( @flaw, "flaw[status]" => (@flaw.status == 'enable' ? "disable" : "enable")  ) %>');
Alertify.log.success('更新完成');