config/routes.rb
Hanjay::Application.routes.draw do

  

  
  resources :news, :only => [:index, :show]
 
  match "/admin/createAdmin" => "admin#createAdmin", :via => :post
  match '/admin/showAdmins' => 'admin#showAdmins' 
  match '/admin/deleteAdmin/:id' => 'admin#deleteAdmin' , :via => :delete
  
  match "/admin/loginCheck" => "admin#loginCheck", :via => :post
  match "/admin/update" => "admin#update", :via => :put
  match '/admin' => 'admin/news#index'    
  
  namespace :admin do
    get "sign_up", "log_in", "log_out", "edit"
    

    resources :events
    resources :flaws

    resources :news, :except => :new do
      match 'uploadPhoto' => 'news#createPhoto', :via => [:post]
      match 'deletePhoto/:id' => 'news#destroyPhoto', :via => [:delete]
    end
    
  end

  resources :flaws
  resources :events
  
  match "pages/:id"		=> "static_page#show"
  resources :pages, :only => :show
  
  resources :news, :only => [:index, :show]
  
  root :to => "static_page#index"
  
  
end

app/views/layouts/_footer.html.erb

<aside _height="none">
  <section>
    <h6>網路安全風險診斷專家</h6>
    <nav><a href="<%= root_url %>">首頁</a> ｜ <a href="<%= page_path( :support ) %>">支援與服務 </a>｜<a href="<%= news_index_path %>">最新消息 </a>｜ <a href="<%= flaws_path %>">安全弱點通報 </a>｜ <a href="<%= events_path %>">漢杰活動</a></nav>
   <div id="info"> 漢杰科技股份有限公司<br>
  11052 台北市信義區基隆路二段 22 號 6 樓之 6<br>
  電話：02-2910-1125</div>
  </section>
</aside>

<footer _height="none">
  <section>©2014 HANJAY. All Right Reserved.     <a href="http://www.summers.com.tw" target="_blank" title="網頁設計 By 夏天廣告">網頁設計 By 夏天廣告</a> </section>
</footer>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<%= stylesheet_link_tag "RWD/desktop" %>
<![endif]-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />
<title>漢杰後台管理系統</title>
<%= stylesheet_link_tag "admin/reset" %>

<%= stylesheet_link_tag "admin/default" %>
<%= stylesheet_link_tag "RWD/mobile", :media => "screen and (max-width: 543px)" %>
<%= stylesheet_link_tag "RWD/tablet", :media => "screen and (min-width: 544px) and (max-width: 896px)" %>
<%= stylesheet_link_tag "RWD/desktop", :media => "screen and (min-width: 897px)" %>
<!--[if lt IE 9]>
<%= stylesheet_link_tag "RWD/desktop", :media => "screen and (min-width: 897px)" %>
<![endif]-->

<%= stylesheet_link_tag "alertify" %>

<%= stylesheet_link_tag "admin/custom" %>
<%= stylesheet_link_tag "admin/jquery-ui" %>

<%= javascript_include_tag "admin" %>

<%= csrf_meta_tags %>
  
<script>
  $(function() {	
	$(".delete a").click(function() {
	/*
		Alertify.dialog.confirm("確定要刪除嗎？", function () {
    	// user clicked "ok"
		}, function () {
    	// user clicked "cancel"
		});
		*/
	});
	
  });
  
  function alertifyConfirm(message) {	  
	Alertify.dialog.confirm("確定要刪除嗎？", function () {
	// user clicked "ok"
		return true;
	}, function () {
	// user clicked "cancel"
		return false;
	});
  }
  $(document).ready(function() {
  
  <% if notice %>
  	Alertify.log.success("<%= notice %>");  
  <% end %>
  
  $('.datePicker').datepicker({
	  dateFormat: "yy-mm-dd"
  });
  /*
	  $.rails.confirm = function(message) { 
	  	return alertifyConfirm(message); 
	  };
  */
  });
</script>
</head>

<body>
<header _height="none">
  <section id="top"> <a id="nav-ctrl"><img src="<%= image_path("nav.png") %>"></a>
    <div class="left">
      <h1><a href="<%= admin_path %>">漢杰後台管理系統</a></h1>
    </div>

    <!--left-->
    <aside> <a id="aside-ctrl"><img src="<%= image_path("set.png") %>"></a>
      <div id="aside-box"><a href="/admin/edit">修改個人資料</a> <a href="/admin/log_out">登出</a> <a href="<%= root_url %>">返回首頁</a> </div>
    </aside>
  </section>
  <!--top--> 
</header>
<section id="main" _height="auto">
  <nav>
    <ul>
      <li <%= ' class="active"'.html_safe if params[:controller] == "admin/news" %>><a href="<%= admin_news_index_path %>" id="nav-1">最新消息</a></li>
      <li <%= ' class="active"'.html_safe if params[:controller] == "admin/flaws" %>><a href="<%= admin_flaws_path %>" id="nav-2">弱點通報</a></li>
      <li <%= ' class="active"'.html_safe if params[:controller] == "admin/events" %>><a href="<%= admin_events_path %>" id="nav-3">漢杰活動</a></li>
      <li <%= ' class="active"'.html_safe if params[:controller] == "admin" %>><a href="<%= admin_path + '/showAdmins' %>" id="nav-4">使用者管理</a></li>
    </ul>
  </nav>
  <article>    
	  	<%= yield %>    
  </article>
</section>

<!--main-->
<footer _height="none"> Copyright © <a href="http://www.summers.com.tw/" target="_blank">Summers</a> </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="Robots" content="index,follow"/>

<meta http-equiv="content-language" content="zh-TW" />
<link rel="SHORTCUT ICON" href="/images/favicon.ico"/>
<link rel="image_src" href="/images/thumb.jpg"/>
<meta property="og:image" content="www.hanjay.com/images/thumb.jpg"/>
<meta property="og:type" content="company"/>
<meta name="google-site-verification" content="QvFuzKbLBaXARSFAOzJm56CdUEoR5QAoI3fyudVb90w" />



<%= render :partial => 'meta' %>
  
<%= stylesheet_link_tag "reset", :media => :all %>
<%= stylesheet_link_tag "application" %>
<%= stylesheet_link_tag "style", :media => :all %>

<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40239827-1', 'hanjay.com');
  ga('send', 'pageview');

</script>
</head>
<body>


<script>

	function setMenu(menu) {
		$('nav a.active').removeClass('active');
		$('nav a[href*="' + menu + '"]').addClass('active');
	}
	
	
	$(document).ready(function() {
		setMenu("<%= params[ :controller ] %>");
		
	});
	
</script>

<header _height="none">
  <section>
    <h1><a href="<%= root_url %>">HANJAY</a></h1>
    
    <nav> <a href="<%= news_index_path %>">最新消息</a> <a href="<%= flaws_path %>">安全弱點通報</a> <a href="<%= page_path( :id => "support" ) %>">支援與服務</a> <a href="<%= root_url + '#service-link' %>">漢杰服務</a> </nav>
    
  </section>
</header>


<article>
  <%= yield %>
</article>

<%= render :partial => "layouts/footer" %>

</body>
</html>